### ISSUE TITLE
workaround for streamed PUT with digest authorization

### ISSUE THREAD

**Issue by dkocher** [lookfirst/sardine#103]
_Original author: jan.ras...@gmail.com (July 01, 2011 15:04:23)_

I thought I'd share a very easy workaround for streamed PUT with digest authorization.

If you try to PUT from a stream to a server that uses Digest authorization, the operation will fail, because the authorization handling will cause &quot;org.apache.http.client.NonRepeatableRequestException: Cannot retry request with a non-repeatable request entity.&quot;

Semi-precise explanation of this issue: Issuing a PUT from a stream leads to the httpclient library using a non-repeatable (streamed) entity. But the authorization process makes the library to repeat the request (1. try unauthorized, 2. server say 401 Unauthorized, use Digest, 3. client retries with Digest, but this will fail, due to the nature of non-repeatable streamed entity).

The workaround is simply to first issue Sardine.exists(...) on the same file you try to PUT. This will cause the Digest authorization to be handled on a request that can be repeated. After this you can perform the PUT operation where the authorization will already be properly established.

Maybe this should be added to Wiki or to the documentation, I am not really sure. Hopefully this will help someone who ran into the same issue as me.

_Original issue: http://code.google.com/p/sardine/issues/detail?id=103_

**Comment by pavelsalamon** [comment]
The exists() trick stopped working in 2016 when a fresh HttpContext started to be created for every request: https://github.com/lookfirst/sardine/commit/fe54ba82e6f4fd1dfe95d3a401fb43c35852adcf

The auth cache entry created by exists() is no longer used for the subsequent put(). I'm pretty sure it doesn't matter if Basic or Digest is used, it just doesn't work anymore.

I too managed to workaround it by enabling pre-emptive auth: Sardine.enablePreemptiveAuthentication(). Beware that this only works for Basic auth.
If you need different auth working you probably have to switch to byte[] entities.
