### ISSUE TITLE
File getting corrupted on Put operation on .doc/.xls(old office format) request from linux weblogic 

### ISSUE THREAD

**Issue by balap6** [lookfirst/sardine#197]
File getting corrupted on Put operation on .doc/.xls(old office format) request from linux weblogic 

Tried with different mimeType options as well octet steam / application/ms-word

sardine.put( destinationUrl, sourceInputStream, mimeType );
sardine.put( destinationUrl, sourceByteArrsy, mimeType );

Whether any configuration or changes required for this linux weblogic.

Same file is working fine in Windows environment

**Comment by lookfirst** [comment]
Please discuss this on the mailing list.

Can you also send a larger code sample to the mailing list? How are you opening and reading the file bytes?
