### ISSUE TITLE
Tests failing

### ISSUE THREAD

**Issue by olivierlemasle** [lookfirst/sardine#198]
4 unit tests are failing:

testLockUnlock(com.github.sardine.LockTest): Unexpected response
testAddPropertyDefaultNamespace(com.github.sardine.ProppatchTest): Unexpected response
testRemovePropertyCustomNamespace(com.github.sardine.ProppatchTest): Unexpected response
testAddPropertyCustomNamespace(com.github.sardine.ProppatchTest): Unexpected response

They're probably linked to a change on http://sudo.ch/.

**Comment by lookfirst** [comment]
Yea... maybe we should just X out those tests for now... PR?

**Comment by lookfirst** [comment]
@dkocher ?

**Comment by dkocher** [comment]
I could setup a test environment that is more stable. Will make a pull request for this if you want.
