### ISSUE TITLE
Build fails on test

### ISSUE THREAD

**Issue by kosek** [lookfirst/sardine#202]
Hi, 

I just want to build library myself and after mvn package I got the following errors:

[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building Sardine WEBDAV client 5.5-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-enforcer-plugin:1.0:enforce (enforce-maven) @ sardine ---
[INFO] 
[INFO] --- maven-resources-plugin:2.5:resources (default-resources) @ sardine ---
[debug] execute contextualize
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 1 resource
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ sardine ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 113 source files to e:\src\sardine\target\classes
[WARNING] Note: e:\src\sardine\src\main\java\com\github\sardine\impl\SardineImpl.java uses or overrides a deprecated API.
[WARNING] Note: Recompile with -Xlint:deprecation for details.
[INFO] 
[INFO] --- maven-resources-plugin:2.5:testResources (default-testResources) @ sardine ---
[debug] execute contextualize
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory e:\src\sardine\src\test\resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:testCompile (default-testCompile) @ sardine ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] --- maven-surefire-plugin:2.10:test (default-test) @ sardine ---
[INFO] Surefire report directory: e:\src\sardine\target\surefire-reports

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running com.github.sardine.AuthenticationTest
Tests run: 7, Failures: 0, Errors: 0, Skipped: 1, Time elapsed: 0.044 sec
Running com.github.sardine.DavResourceTest
Tests run: 12, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.013 sec
Running com.github.sardine.FunctionalSardineTest
Tests run: 26, Failures: 0, Errors: 0, Skipped: 2, Time elapsed: 0.01 sec
Running com.github.sardine.impl.handler.MultiStatusResponseHandlerTest
10.4.2015 18:26:29 com.github.sardine.DavResource getContentLength
WARNING: Failed to parse content length 
10.4.2015 18:26:29 com.github.sardine.DavResource getContentLength
WARNING: Failed to parse content length 
Tests run: 6, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.274 sec
Running com.github.sardine.LockTest
Tests run: 3, Failures: 0, Errors: 1, Skipped: 1, Time elapsed: 0.622 sec <<< FAILURE!
Running com.github.sardine.ProppatchTest
Tests run: 3, Failures: 0, Errors: 3, Skipped: 0, Time elapsed: 0.833 sec <<< FAILURE!
Running com.github.sardine.SardineUtilTest
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0 sec

Results :

Tests in error: 
  testLockUnlock(com.github.sardine.LockTest): Unexpected response
  testAddPropertyDefaultNamespace(com.github.sardine.ProppatchTest): Unexpected response
  testRemovePropertyCustomNamespace(com.github.sardine.ProppatchTest): Unexpected response
  testAddPropertyCustomNamespace(com.github.sardine.ProppatchTest): Unexpected response

Tests run: 59, Failures: 0, Errors: 4, Skipped: 4

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 4.003s
[INFO] Finished at: Fri Apr 10 18:26:31 CEST 2015
[INFO] Final Memory: 8M/23M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.10:test (default-test) on project sardine: There are test failures.
[ERROR] 
[ERROR] Please refer to e:\src\sardine\target\surefire-reports for the individual test results.
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

**Comment by lookfirst** [comment]
duplicate #198
