### ISSUE TITLE
Cannot enable preemptive authentication for multiple ports

### ISSUE THREAD

**Issue by jochenberger** [lookfirst/sardine#206]
It is currently not possible to enable preemptive authentication for multiple HTTP or multiple HTTPS ports. There is `com.github.sardine.impl.SardineImpl.enablePreemptiveAuthentication(String, int, int)` (#181), but if that's called multiple times, the old `AuthCache` is cleared. The method should check if there is already an `AuthCache` present and extend it in that case.
Unfortunately, I cannot override the method and add that behavior because I'd need to access `com.github.sardine.impl.SardineImpl.context` which is private.

**Comment by lookfirst** [comment]
Closed with  #207
