### ISSUE TITLE
PROPPATCH cannot set new complex properties (only text properties are currently supported)

### ISSUE THREAD

**Issue by olivierlemasle** [lookfirst/sardine#208]
`Sardine.patch(...)` uses `Map<QName, String> setProps` to set new properties.

This limits the feature to simple textual properties only.

It excludes complex properties, as show in the WebDAV spec example:
http://www.webdav.org/specs/rfc4918.html#rfc.section.9.2.2

For example, it is not possible, using Sardine, to add an Owncloud tag, because Owncloud tags format is:

```xml
<?xml version="1.0"?>
<d:propertyupdate xmlns:d="DAV:" xmlns:oc="http://owncloud.org/ns">
  <d:set>
    <d:prop>
                <oc:tags>
                        <oc:tag>tag1</oc:tag>
                        <oc:tag>tag2</oc:tag>
                </oc:tags>
                <oc:favorite>1</oc:favorite>
    </d:prop>
  </d:set>
</d:propertyupdate>
```

**Comment by lookfirst** [comment]
Closing cause there is a PR to track this.
