### ISSUE TITLE
Cannot build Sardine because tests fail

### ISSUE THREAD

**Issue by smillies** [lookfirst/sardine#212]
I just cloned the repository and issued a "mvn install" on my local machine. There are 7 tests that have errors. Is it my mistake?

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running com.github.sardine.impl.handler.MultiStatusResponseHandlerTest
Tests run: 6, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.035 sec
Running com.github.sardine.SardineUtilTest
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.032 sec
Running com.github.sardine.AuthenticationTest
Tests run: 7, Failures: 0, Errors: 0, Skipped: 1, Time elapsed: 0.032 sec
Running com.github.sardine.DavResourceTest
Tests run: 12, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.022 sec
Running com.github.sardine.LockTest
Tests run: 3, Failures: 0, Errors: 3, Skipped: 0, Time elapsed: 1.709 sec <<< FAILURE!
Running com.github.sardine.ProppatchTest
Tests run: 4, Failures: 0, Errors: 4, Skipped: 0, Time elapsed: 0.778 sec <<< FAILURE!
Running com.github.sardine.FunctionalSardineTest
Tests run: 26, Failures: 0, Errors: 0, Skipped: 2, Time elapsed: 0.043 sec

Results :

Tests in error:
  testLockFailureNotImplemented(com.github.sardine.LockTest)
  lockRefreshUnlock(com.github.sardine.LockTest)
  testLockUnlock(com.github.sardine.LockTest)
  testAddPropertyDefaultNamespace(com.github.sardine.ProppatchTest)
  testRemovePropertyCustomNamespace(com.github.sardine.ProppatchTest)
  testAddPropertyCustomNamespace(com.github.sardine.ProppatchTest)
  testAddCustomComplexProperties(com.github.sardine.ProppatchTest)

Tests run: 60, Failures: 0, Errors: 7, Skipped: 3

[INFO] ------------------------------------------------------------------------
[ERROR] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] There are test failures.

**Comment by dkocher** [comment]
Fixed in b1264a30247275897235d380c222dcad201beea8.
