### ISSUE TITLE
SardineException message should contain status code and response phrase

### ISSUE THREAD

**Issue by jochenberger** [lookfirst/sardine#218]
When a SardineException is thrown with a status code and a reason phrase (e.g. by ValidatingResponseHandler), the code and reason should be included in the exception message so it gets logged if the SardineException is somewhere down the exception stack. Currently you only get
```
com.github.sardine.impl.SardineException: Unexpected response
        at com.github.sardine.impl.handler.ValidatingResponseHandler.validateResponse(ValidatingResponseHandler.java:48) ~[ValidatingResponseHandler.class:5.5]
...
```
That makes it hard to debug the problem.

**Comment by sardineuser** [comment]
the code is available in ex.getStatusCode(), and the entire phrase is available in ex.toString().

**Comment by jochenberger** [comment]
@dkocher the issue is still there. As I said: "the code and reason should be included in the *exception message*" as that is what most logging frameworks include in their output.
