### ISSUE TITLE
updated webdav.xsd?

### ISSUE THREAD

**Issue by dankarp** [lookfirst/sardine#221]
There are a bunch of classes in `com.github.sardine.model` that appear to be generated but which don't appear to be referenced in `webdav.xsd`. Is there a more recent version of `webdav.xsd` that isn't checked in, or are these classes actually hand-tooled?

**Comment by lookfirst** [comment]
Yea... it was the basis and the generated code has been added to and modified since. It is a royal pain in the ass to generate code from a xsd.

**Comment by lookfirst** [comment]
Since this isn't really an issue, I'm going to close it. If you'd like to discuss things further, please do so on the mailing list. Also, if you'd like to build an easy to run system to generate all the code from an updated xsd file, PR's are welcome. =)
