### ISSUE TITLE
Android SDK 23 no longer uses org.apache.http.client

### ISSUE THREAD

**Issue by SafetyMarcus** [lookfirst/sardine#233]
I can't tell from the issues that were logged if someone has reported this before but, in Android SDK 23 (Marshmallow) Android dropped native support for HttpClient, which seems to be used extensively throughout the library (for example in your put requests). Is there some solution to this or are there plans to support Android SDK 23 and `URLConnection`?

**Comment by dkocher** [comment]
Why not just bundle the `org.apache.httpcomponents` dependency?
