### ISSUE TITLE
httpClient and httpClientBuilder are private in SardineImpl

### ISSUE THREAD

**Issue by chudzikp** [lookfirst/sardine#242]
Fields:
com.github.sardine.impl.SardineImpl#client
com.github.sardine.impl.SardineImpl#builder
are private. In situations when I'm forced to overwrite execute methods (I'm having weird issues regarding shared HttpClientContext and multiple simultaneous request when using sharepoint webdav):
com.github.sardine.impl.SardineImpl#execute(org.apache.http.client.methods.HttpRequestBase, org.apache.http.client.ResponseHandler<T>)
com.github.sardine.impl.SardineImpl#execute(org.apache.http.client.methods.HttpRequestBase)
I'm unable to use httpClient and then what is the point of having protected (overwritable methods) when you can not access fields required to make anything useful in those methods?)

Why is httpClient private (builder I can understand, after all I can inject it using constructor) but why I can't access httpClient?

**Comment by dkocher** [comment]
You can inject your own client instance by calling the constructor with the `HttpClientBuilder` argument.

**Comment by chudzikp** [comment]
Yes I know I can inject my own client using httpClientBuilder. But I don't want to mess with httpClient. Default client build by sardine is ok. All I want is possibility to modify behavior inside execute methods and without easy access to httpClient there is no easy way to achieve it. 
You provide protected execute methods but you don't provide way for actual modification what is the point of having something visible if you can not use it? If those methods are not meant to be overwritten then you should mark them final or make private.

**Comment by dkocher** [comment]
It might help to call `#disablePreemptiveAuthentication` to clear the authentication state.

**Comment by dkocher** [comment]
To allow fiddling with the context we would need to overload the `#execute` methods with a `HttpClientContext` argument I suppose or allow to set a custom context.

**Comment by dkocher** [comment]
Pull requests welcome.
