### ISSUE TITLE
Sardine.List()  extremly slow

### ISSUE THREAD

**Issue by 3edc** [lookfirst/sardine#245]
Hi  all,
I'm connecting to a WEBDAV Server that contains about 1000 files in one directory. 

Sardine.list() needs around 9 mins to read that. During the list() call, the method is blocked.

CarotDAV- Webdav client needs ~ 12secs  for the same.  So its not a server issue.

Does anybody know why it's so slow ?

Thanks
Gerry

**Comment by lookfirst** [comment]
Please confirm that it is not Sardine by executing the same commands directly against the server.

**Comment by 3edc** [comment]
Hi , 
thanks for the response.

I did that already as said above. I used WEBDAV client ["CarotDAV"](http://rei.to/carotdav_en.html) to list towards the same server and as said, it needs seconds to list the same contents.

Thx
Gerry.

**Comment by lookfirst** [comment]
Weird, let us know when you find out.

**Comment by 3edc** [comment]
Ok, solved. 
Its a JVM issue. 

On a WIN7 with JVM8-66 it  takes 3 secs for the listing, but with 80% CPU. Obviously the XML parsing kills him. 

On the targeted machine (ODROID C1 - a Raspberry clone) also with  JVM8-66  it takes indeed ~ 9 mins to get the same results. 

I will try to used the davdroid lib, perhaps its not so ressource hungry. 

Thanks for everybody to take care.  No issue any more, this can be closed.
Have a nice weekend ! 
Gerry

**Comment by lookfirst** [comment]
Beware, davdroid is gplv3. It also looks like it only does cal/carddav?

**Comment by 3edc** [comment]
Oops, sorry, meant "Sardine-Android".
But I guess its the same code basis, isn' it ?
