### ISSUE TITLE
Enchancement - Make asTree(URL url)

### ISSUE THREAD

**Issue by deinok** [lookfirst/sardine#246]
Do a method that returns a tree of DavResources like a Tree o FileSystem(DavFolders & DavFiles)

I can give help

**Comment by lookfirst** [comment]
Send a PR please. =)

**Comment by deinok** [comment]
Okey

**Comment by deinok** [comment]
@lookfirst Probably I will need to extend DavResources to DavFolder and DavFile, any problem with this?

**Comment by lookfirst** [comment]
I don't really understand what you are trying to do.

**Comment by deinok** [comment]
Something like a FileSystem

http://shurimages.com/u/2IhgPX97Ss.jpg

http://shurimages.com/u/Udn12OtrLl.png

**Comment by deinok** [comment]
I send a commit with the implementation @lookfirst

**Comment by lookfirst** [comment]
I get what you are trying to create. I don't get why you need to modify DavResource in order to do so. Just wrap it. DavResource already has isDirectory().
