### ISSUE TITLE
The tests are using googlecode's WebDAV

### ISSUE THREAD

**Issue by sjsf** [lookfirst/sardine#261]
...which apparently has been shut down.

**Comment by LotharSpiegel** [comment]
Hi! Would it be of interest (as pull request) to introduce https://www.testcontainers.org/ to make the tests independent from the availability of any online test Webdav? I've tried it out and it would be feasible.

**Comment by lookfirst** [comment]
Improvements are always welcome. I do worry about a dependency on a third
party service though. This project is so old that it tends to even outlast
hosting services. We started on google code!
