### ISSUE TITLE
SardineImpl not thread safe - HttpClientContext reused and mutated

### ISSUE THREAD

**Issue by adammichalik** [lookfirst/sardine#263]
Sardine [claims to be thread-safe](https://github.com/lookfirst/sardine/wiki/UsageGuide#threading) and the `HttpClient`+`PoolingHttpClientConnectionManager` are indeed thread-safe, but the `HttpClientContext` class is not. The `SardineImpl.context` field is reused for each request and is mutated during the request processing which may lead to race conditions and weird exceptions like this one: https://issues.apache.org/jira/browse/HTTPCORE-437

**Comment by adammichalik** [comment]
I believe the issue could be remedied if `new BasicHttpContext(this.context)` was passed to `client.execute()` in `SardineImpl.execute()` methods. That is on condition that the `SardineImpl.context` is not modified any more after the `SardineImpl` instance has been constructed and configured. The `BasicHttpContext` will provide read-only access to the attributes of `SardineImpl.context`, but all the mutations will be applied only to that `BasicHttpContext` instance. Also, it would probably allow to remove the two 

```java
this.context.removeAttribute(HttpClientContext.REDIRECT_LOCATIONS);
```

lines in `SardineImpl`, because the `SardineImpl.context` would never be polluted during the request execution.

**Comment by dkocher** [comment]
That sounds sane. Can you provide a patch?

**Comment by adammichalik** [comment]
@dkocher Any chance of releasing this some time soon?

**Comment by dkocher** [comment]
@lookfirst is doing the release management. We have a separate release cycle in https://github.com/iterate-ch/sardine.

**Comment by sadiksikder** [comment]
can anyone GET method properly with coe explain?
please
i have written a code 
sardine.get("server location patg");

the code works but where it is actually downloaded i didnt see....
