### ISSUE TITLE
Is there any way to update resource name/file name using sardine client?

### ISSUE THREAD

**Issue by UmeshRajani** [lookfirst/sardine#272]
Currently I am updating filename by taking file content in temporary inputstarem and then delete that file and again add that content with new name. and it is very wrong way is there any workaround to update filename using sardine client.

**Comment by rafaelleru** [comment]
just use move:
https://github.com/lookfirst/sardine/wiki/UsageGuide#void-movestring-sourceurl-string-destinationurl

**Comment by UmeshRajani** [comment]
Yes it works. Thanks.
