### ISSUE TITLE
What Url I need for acces nextclud/owncloud server??

### ISSUE THREAD

**Issue by rafaelleru** [lookfirst/sardine#275]
I don't know if I must use the webdab://server.url... or only the http link and sardine will make the work for me.

**Comment by trexguo** [comment]
your-URL-to-Owncloud/remote.php/webdav

**Comment by rafaelleru** [comment]
Thanks

**Comment by eskalera** [comment]
Hi @rafaelleru 
Have you managed to connect to your owncloud instance from Sardine?

I am trying to but with the url mentioned by @trexguo it keeps returning 
`Attempt to invoke virtual method 'java.util.List de.aflx.sardine.model.Multistatus.getResponse()' on a null object reference`

If I run `curl -X PROPFIND -u user:password "http://myowncloud_domain/remote.php/webdav/" ` I get a correct response though.
