### ISSUE TITLE
Preemptive authentication does not work when only setting the host 

### ISSUE THREAD

**Issue by tommix000** [lookfirst/sardine#285]
public void enablePreemptiveAuthentication(String hostname)

populates the AuthCache using the port numbers -1 and preemptive authentication does not happen when using the default ports 80/443.

 It works by calling Sardine#enablePreemptiveAuthentication(host, 80, 443);

**Comment by kkofler** [comment]
Note that this also affects `enablePreemptiveAuthentication(URL)` when using a URL of the form `https://dav.example.com` as opposed to `https://dav.example.com:443`, see [the implementation of `enablePreemptiveAuthentication(URL)`](https://github.com/lookfirst/sardine/blob/3e0c98daada92b915d03f16f58a98ef00c106627/src/main/java/com/github/sardine/impl/SardineImpl.java#L330) and [the Javadoc for URL.getPort()](https://docs.oracle.com/javase/7/docs/api/java/net/URL.html#getPort()) (it returns `-1` when not explicitly set).

**Comment by lookfirst** [comment]
This is so old, I don't remember why we ended up with -1 there... it does seem like a huge amount of code smell to do that, but I have a feeling it was to work around some issue in HttpClient which may or may not be long resolved. Again, happy to accept a PR if you can figure this all out.

**Comment by kkofler** [comment]
It is possible that you might actually need to add cache entries both for -1 and for the real default port, though I hope not.

**Comment by kkofler** [comment]
Darn, the issue number is wrong there!
