### ISSUE TITLE
each calling will send two request

### ISSUE THREAD

**Issue by zarknight** [lookfirst/sardine#286]
I found that each calling of method such as list, put, get will send two request to the webdav server. Here is my code: 

```
public class TestDav {
    public static void main(String[] args) throws IOException {
        Sardine sardine = SardineFactory.begin("webdav1", "test");
        List<DavResource> list = sardine.list("http://192.168.11.134:80/1043598432176128/test/");
        System.out.println(list);
    }
}
````

And this is my webdav server's log:
```
192.168.11.2 - - [07/Dec/2017:15:31:36 +0800] "PROPFIND /1043598432176128/ HTTP/1.1" 401 381 "-" "Sardine/5.8"
192.168.11.2 - webdav1 [07/Dec/2017:15:31:36 +0800] "PROPFIND /1043598432176128/ HTTP/1.1" 207 3195 "-" "Sardine/5.8"
```

The first request always return HTTP 401, and the second one return the expected result. Is there any way to avoid that?

Thanks.

**Comment by lookfirst** [comment]
Yes, this is how HTTP Auth works. [A helpful page with a diagram](https://developer.mozilla.org/en-US/docs/Web/HTTP/Authentication
).

I'm going to close this because it isn't a bug. Feel free to continue the discussion though.

**Comment by zarknight** [comment]
Thank you.
