### ISSUE TITLE
Allow to pass headers for all methods

### ISSUE THREAD

**Issue by KajanM** [lookfirst/sardine#302]
`put` and `get` are overloaded to accept headers
https://github.com/lookfirst/sardine/blob/d71beef1ffbf3df4095f5f59e5d46ceabb904191/src/main/java/com/github/sardine/Sardine.java#L179

It will be great to do the same for other methods as well.
For example
https://github.com/lookfirst/sardine/blob/d71beef1ffbf3df4095f5f59e5d46ceabb904191/src/main/java/com/github/sardine/Sardine.java#L294
In my case, I had to pass an access token via `Authorization` header and I do not have access to user credentials.

**Comment by lookfirst** [comment]
It is better to do this at the HttpClient level so that we don't have to add the overloads everywhere. Going to close this as a wontfix. Sorry!
