### ISSUE TITLE
FileId

### ISSUE THREAD

**Issue by matiasperes23** [lookfirst/sardine#305]
Hi I would like to know how to get the Id of a file. Thanks

**Comment by dkocher** [comment]
WebDAV has no concept of file IDs.

**Comment by matiasperes23** [comment]
Thanks for the reply,

Yes there is, I need it to list all file versions:
https://docs.nextcloud.com/server/14/developer_manual/client_apis/WebDAV/versions.html

*|* Ing. Matias Péres
*Software Engineer*
*m*: +598 94303043
*s*: bdi_sky
