### ISSUE TITLE
Using HTTP Proxy with authentication, the wrong credentials are used

### ISSUE THREAD

**Issue by DJGummikuh** [lookfirst/sardine#308]
We have the following construction:
SQUID Proxy with mandatory authentication
Owncloud with authentication.

When using Sardine, the proxy server gets handed the login data for OWNCLOUD, not the ones for the proxy authentication. We are providing the authentication credentials to the java authenticator but it never gets pulled, I assume the underlying proxy library you use does not take its credentials from there.

Could you please add support for proxies with authentication?

**Comment by DJGummikuh** [comment]
Issue is that the CredentialsProvider gets preset with one set of credentials for any host, any port etc. I'll create a pull request with altered setup that includes proxyuser proxy pass proxy host and proxy user for these purposes.

**Comment by DJGummikuh** [comment]
Here is a patch that works for us and provides the behavior we need. Could you please test and merge it (and create a new release for us to base off from with our local fork?)
[authentication.patch.txt](https://github.com/lookfirst/sardine/files/2788278/authentication.patch.txt)

**Comment by DJGummikuh** [comment]
*bump*

**Comment by lookfirst** [comment]
Why not just call setCredentials() yourself?

https://github.com/lookfirst/sardine/blob/master/src/main/java/com/github/sardine/impl/SardineImpl.java#L256

**Comment by lookfirst** [comment]
Just some super friendly feedback as well... open source projects are maintained by volunteers. The best way to effect change is to lower the barriers for those volunteers to the absolute minimum. 

Uploading a diff as a file is about as 1990's tech as you can get and pretty much guaranteed to be ignored. Put yourself in our shoes, would you pay attention to that in your busy schedule?

In the least, you should create an actual Github PR. That PR should generally contain a minimum amount of code changes (with accurate formatting according to the existing general style of the project), reasoning, documentation updates, tests and whatever else would give your PR the highest chances of being accepted.

Cheers!

**Comment by DJGummikuh** [comment]
Hey!
Thanks for the answers!
Regarding the setCredentials Method we must have missed it when we tried to figure out how to solve the issue. Will have to investigate further.

The patch instead of a pull request came from the fact that our local "fork" was actually by mistake not properly forked but checked out, then committed to an internal repository without history or original origin, making it impossible to push the changes back to you. I wll take a look at the setCredentials call and if it works as intended we can just drop this issue.

**Comment by DJGummikuh** [comment]
We tested it and the setCredentials Method does indeed fix our issue. I do not understand how we missed it. This issue can therefore be closed.
