### ISSUE TITLE
One bad SUPPORTED_DATE_FORMATS in SardineUtil

### ISSUE THREAD

**Issue by cyquicri** [lookfirst/sardine#317]
There is a typo error in one of the SUPPORTED_DATE_FORMATS in com.github.sardine.util.SardineUtil
line 51 `"yyyy-MM-dd'T'HH:mm:ss.sss'Z'",` should be `"yyyy-MM-dd'T'HH:mm:ss.SSS'Z'",` 
(sss -> SSS )
Therefore date with millisecond are not parsed correctly at the moment.

**Comment by lookfirst** [comment]
@cyquicri Holy shit, that is a 10 year old bug. Nice find!

**Comment by lookfirst** [comment]
[Blame going back in time](https://github.com/lookfirst/sardine/blame/8b44a5bdde9c4cd3b4d15f95d14db06c411d1e96/src/com/googlecode/sardine/util/SardineUtil.java)
