### ISSUE TITLE
Java 11 Compatibility

### ISSUE THREAD

**Issue by hgurule** [lookfirst/sardine#321]
Hi, I'm trying to use this library with Java 11 and running into a jaxb error.

```
Caused by: javax.xml.bind.JAXBException: Implementation of JAXB-API has not been found on module path or classpath.
 - with linked exception:
[java.lang.ClassNotFoundException: com.sun.xml.internal.bind.v2.ContextFactory]
```

It seems like the most recent commit here https://github.com/lookfirst/sardine/pull/320 fixes this issue, so would it be possible to publish a new release so I can use this library with Java 11? Thanks!

**Comment by lookfirst** [comment]
A release has been published. Thanks!
