### ISSUE TITLE
Weak XML Schema: Undefined Namespace

### ISSUE THREAD

**Issue by QiAnXinCodeSafe** [lookfirst/sardine#331]
Specifying a namespace of ##any in the <any> element means the schema allows elements beyond what is explicity defined in the schema, thereby making it easer to craft malicious documents.
https://github.com/lookfirst/sardine/blob/e91fb8b4cdf81bdfaaf909018124ec536e9ecbdf/webdav.xsd#L155

**Comment by lookfirst** [comment]
Thanks for your report. This is in an error response element and has been in this codebase for about 11 years now without a single reported issue. I'm not too worried about it. I'm going to close this as no-need-to-fix.
