### ISSUE TITLE
Wrong parameter in DavQuota of SardineImpl 

### ISSUE THREAD

**Issue by jithutintu** [lookfirst/sardine#342]
Hello ,
Here in below piece of code in SardineImpl the constructor of DavQuota expect response .but the parameter passed is DavResource resource in below code.

```
if (resource.getStatusCode() == 200) return new DavQuota(resource);
```

Could you please rectify it?

Thanks

**Comment by LotharSpiegel** [comment]
See pull request: https://github.com/lookfirst/sardine/pull/344

**Comment by dkocher** [comment]
The existing code passes the required type `Response` and I cannot spot any error.

**Comment by LotharSpiegel** [comment]
The existing code passes in the following line:
```
if (resource.getStatusCode() == 200) return new DavQuota(resource);
```
an object of type `DavResource` to the constructor of `DavQuota` instead of sth. of type `Response` as needed.
