### ISSUE TITLE
Unable to compile the latest release

### ISSUE THREAD

**Issue by TheDistributedDev** [lookfirst/sardine#345]
Hello,

I've cloned the repo and I'm trying to build the latest commit but it appears to cause the following failure.

```
[ERROR] /private/tmp/sardine/src/main/java/com/github/sardine/impl/SardineImpl.java:[701,78] incompatible types: com.github.sardine.DavResource cannot be converted to com.github.sardine.model.Response
```

I'm using the following maven command to perform the build process.
```
mvn assembly:assembly -DdescriptorId=jar-with-dependencies -Dmaven.test.skip=true
```

If I check out the previous commit (462f10a296f725bb41a390a0ea20b3b70b5d988f) it builds just fine. Am I missing something obvious or is there really a bug?

OS: OSX 10.15.7
JAVA: OpenJDK 64-Bit  build 14.0.2+12

**Comment by dkocher** [comment]
Duplicate for #342.
