### ISSUE TITLE
"jakartify" sardine

### ISSUE THREAD

**Issue by MichaelEnke** [lookfirst/sardine#358]
Hi there,
I migrate a project which uses Sardine from Tomcat 9 to Tomcat 10. Since Tomcat changed from javax (9 and before) to the jakarta import namespace, all depending libraries in this project need to be updated to the "jakartified" version. For Sardine there seems to be no jakartified version. Would that be a good reason to create a version 6.0?
Thanks.

**Comment by lookfirst** [comment]
Background: https://www.jetbrains.com/idea/guide/tutorials/migrating-javax-jakarta/background/

**Comment by lookfirst** [comment]
Closed with #360
