### ISSUE TITLE
createDirectory and getResources HTTP/1.1 415 Unsupported Media Type

### ISSUE THREAD

**Issue by dkocher** [lookfirst/sardine#37]
_Original author: BoydEdmo...@NebulaSoftware.com (March 21, 2010 21:43:22)_

<b>What steps will reproduce the problem?</b>
1.sardine.createDirectory
(&quot;http://www.Verasonics.com/VerasonicsWebDav/TestFolder/&quot;);
2.sardine.getResources(&quot;http://www.Verasonics.com/VerasonicsWebDav/&quot;);

<b>What is the expected output? What do you see instead?</b>
Expect the directory to be created.  Instead get an exception.
Expect a directory listing to be returned.  Instead get an exception.

<b>What version of the product are you using? On what operating system?</b>
97, Windows XP SP 3, 32-bit, JRE 1.5 32-bit.

<b>Please provide any additional information below.</b>

Output with exception is listed below.  Looking around a bit in the Java 
debugger, I saw the &quot;415&quot; HTTP error message.

The server is Microsoft IIS.

Other Sardine commands work:
        // X getResources, HTTP/1.1 415 Unsupported Media Type
        // V getInputStream
        // V put, V put
        // V delete
        // X createDirectory, HTTP/1.1 415 Unsupported Media Type
        // X move fails to delete original
        // V copy
        // V exists

SoftwareReleaseTools version 1.3.119
Please provide logon creditials 
for &quot;http://www.Verasonics.com/VerasonicsWebDav/&quot;.
Destination: &quot;http://www.Verasonics.com/VerasonicsWebDav/TestFolder/&quot;
Encoded: &quot;http://www.Verasonics.com/VerasonicsWebDav/TestFolder/&quot;
ERROR!  Exception when accessing WebDAV.  Details:  
com.googlecode.sardine.util.SardineException: The server has returned an 
HTTP error
com.googlecode.sardine.util.SardineException: The server has returned an 
HTTP error
    at com.googlecode.sardine.SardineImpl.createDirectory
(SardineImpl.java:334)
    at 
com.verasonics.softwarereleasetools.SoftwareReleaseTools.copyMexToWebDav
(SoftwareReleaseTools.java:1256)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke
(NativeMethodAccessorImpl.java:39)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke
(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:585)
    at com.verasonics.softwarereleasetools.SoftwareReleaseTools.main
(SoftwareReleaseTools.java:165)

_Original issue: http://code.google.com/p/sardine/issues/detail?id=37_

**Comment by robertoandrade** [comment]
Just in case others like me end up bumping into this issue with other WebDAV clients, my issue wasn't related to Sardine at all, but I noticed my HTTP client was enabling Chunked Encoding by default and my WebDAV server (tried it both on IIS on Windows 10 and Apache on Alpine Linux) didn't like those requests and responded always with a 415, as soon as I disabled chunked encoding on the client, it magically started working!  ¯\_(ツ)_/¯
