### ISSUE TITLE
Release missing in Maven Central

### ISSUE THREAD

**Issue by dkocher** [lookfirst/sardine#420]
Some artifacts for [5.11](https://github.com/lookfirst/sardine/releases/tag/sardine-5.11) uploaded to OSS Sonatype fail verification with `Event: Failed: Signature Validation`

> Missing Signature: '/com/github/lookfirst/sardine/5.11/sardine-5.11-javadoc.jar.asc' does not exist for 'sardine-5.11-javadoc.jar'.
> Missing Signature: '/com/github/lookfirst/sardine/5.11/sardine-5.11-sources.jar.asc' does not exist for 'sardine-5.11-sources.jar'.

Not sure why the GPG signing [^1] did not apply.

[^1]: https://github.com/lookfirst/sardine/blob/434259231c9d21217836d93449c2d462de9a0b96/pom.xml#L224C29-L232

**Comment by lookfirst** [comment]
I set all that stuff up years ago and completely forgot how it is done.

**Comment by dkocher** [comment]
Fixed with df62bab. Pushing previous builds by checking out tag and building with `mvn deploy -Prelease-sign-artifacts`.
