### ISSUE TITLE
Update from Sardine 5.10 to 5.12 breaks SLF4J

### ISSUE THREAD

**Issue by rPraml** [lookfirst/sardine#432]
We use in our application SLF4J 1.7.36, but 5.12 (and also 5.11) have a dependency to SLF4J 2.0 (slf-api + slf-simple) now.

See https://repo1.maven.org/maven2/com/github/lookfirst/sardine/5.10/sardine-5.10.pom
vs. https://repo1.maven.org/maven2/com/github/lookfirst/sardine/5.12/sardine-5.12.pom
 
This change was introduced with
https://github.com/lookfirst/sardine/commit/55ad2d2957d1df57f8d74ce6884a99ff2e814915
I assume, that these dependencies should have the `test` scope.

/edit: Possible workaround: Exclude them in your own application-pom

Roland

**Comment by oliviercailloux** [comment]
SLF4J recommends to not export your provider. So, slf-simple should not be marked as a transitive dependency. This can be done with the test scope, indeed.

Currently, I have to exclude slf-simple from the dependencies of Sardine.

**Comment by dkocher** [comment]
Would you mind to open a pull request with the patch.
