### ISSUE TITLE
Provides transitive vulnerable dependency maven:commons-codec:commons-codec:1.11

### ISSUE THREAD

**Issue by HamusutaW** [lookfirst/sardine#465]
When I added the Sardine dependency in IntelliJ IDEA I got a warning:

Provides transitive vulnerable dependency maven:commons-codec:commons-codec:1.11
[Cxeb68d52e-5509](https://devhub.checkmarx.com/cve-details/Cxeb68d52e-5509/?utm_source=jetbrains&utm_medium=referral&utm_campaign=idea) 3.7 Exposure of Sensitive Information to an Unauthorized Actor vulnerability
Results powered by Checkmarx(c)

**Comment by anibyl** [comment]
I don't think it helped:

```
$ gradle dependencies
...
\--- com.github.lookfirst:sardine:5.13
     +--- org.apache.httpcomponents:httpclient:4.5.14
     |    +--- org.apache.httpcomponents:httpcore:4.4.16
     |    +--- commons-logging:commons-logging:1.2
     |    \--- commons-codec:commons-codec:1.11
```

Sardine depends on an older version of `httpclient` which uses the vulnerable `commons-codec:1.11`.
